(lang dune 3.5)

(name SchemeCallCC)

(generate_opam_files true)

(authors "Denisov Alexey")

(maintainers "Denisov Alexey")

(license LGPL-3.0-or-later)

(package
 (name SchemeCallCC)
 (synopsis "Scheme pareser and interpreter")
 (depends ocaml dune angstrom))
